# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab4f5bf057015faed42ad94c4d19d156150507d1ec4ac019ce40ffe3f6463cc9fa0255584c5e99a86eef73d4d585fab8e9b2517770334fd5e6aaf0a3afad4c64

test:
  secret_key_base: e28220613af6b9468667148933788ee6b88725e6a132d121f97b6a5b36523e2526206aa4b73f5338ac49aa14023ebea147246e138c9abc1070c893937559eef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
